name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Puedes ajustar la versión que necesites

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Construir la aplicación Angular
      - name: Build the Angular app
        run: |
          npm run build --base-href angular-github-actions
        # Nota:
        # El parámetro --base-href se utiliza para que las rutas funcionen correctamente en GitHub Pages.

      # 5. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular-github-actions
